version: "3.2"
services:

  pyspark:
    volumes:
      - $PATH_DEVELOP_SCRIPTS:/home/jovyan/development
      - ./extractor:/home/jovyan/extractor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 8081:8081
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: $JUPYTER_TOKEN
      PYTHONPATH: "/home/jovyan:${PYTHONPATH}"