[tool.ruff]
target-version = "py311"
line-length = 88
select = ["F", "I", "B"]
ignore = ["E501"]

[tool.ruff.format]
indent-style = "space"
quote-style = "single"
line-ending = "lf"
docstring-code-format = true